# Generated by Django 5.2.9 on 2026-03-31 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rate_usd', models.DecimalField(decimal_places=8, help_text='1 unit of this crypto = ? USD', max_digits=20)),
                ('wallet_address', models.CharField(help_text='Wallet address to receive deposits', max_length=255)),
                ('network', models.CharField(blank=True, help_text='Network (ERC20, TRC20, BEP20, etc.)', max_length=50)),
                ('min_deposit_usd', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
                ('max_deposit_usd', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(default='💰', help_text='Emoji icon for display', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cryptocurrencies',
                'ordering': ['sort_order', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rate_used', models.DecimalField(decimal_places=8, max_digits=20)),
                ('wallet_address', models.CharField(max_length=255)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='deposit_qrcodes/')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Confirmed - Pending Admin'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crypto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cryptocurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
