# Generated by Django 5.2.9 on 2026-03-31 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cryptocurrency_cryptodeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Amount in crypto after conversion', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='crypto_currency',
            field=models.ForeignKey(blank=True, help_text='Cryptocurrency to withdraw in', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cryptocurrency'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='rate_used',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used', max_digits=20, null=True),
        ),
    ]
