# Generated by Django 5.2.9 on 2026-03-31 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_withdrawalrequest_crypto_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee amount in USD', max_digits=12),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Fee amount in crypto', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_paid',
            field=models.BooleanField(default=False, help_text='Whether the fee has been paid'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Fee percentage charged', max_digits=5),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='crypto_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='rate_used',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='wallet_address',
            field=models.CharField(max_length=255),
        ),
    ]
