# Generated by Django 5.2.9 on 2026-04-01 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_withdrawalrequest_fee_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('category', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('platinum', 'Platinum'), ('copper', 'Copper'), ('accessories', 'Accessories')], default='gold', max_length=20)),
                ('icon', models.CharField(default='🥇', help_text='Emoji icon for display', max_length=10)),
                ('specification', models.CharField(help_text='e.g., 1 troy oz · .9999 Au', max_length=200)),
                ('purity', models.CharField(help_text='e.g., .9999 (24kt)', max_length=50)),
                ('weight', models.CharField(help_text='e.g., 1 troy oz / 31.1g', max_length=100)),
                ('mint', models.CharField(help_text='e.g., US Mint, PAMP Suisse', max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('spot_price', models.DecimalField(decimal_places=2, help_text='Market spot price', max_digits=20)),
                ('price_change_24h', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='physical_products/')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('service_type', models.CharField(choices=[('vault', 'Qubix Vault'), ('shipped', 'Shipped to Address')], default='vault', max_length=10)),
                ('vault_location', models.CharField(default='Zurich, Switzerland', max_length=100)),
                ('is_insured', models.BooleanField(default=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('delivery_status', models.CharField(choices=[('processing', 'Processing'), ('confirmed', 'Confirmed'), ('packaged', 'Packaged'), ('transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='processing', max_length=50)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_holdings', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.physicalproduct')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_type', models.CharField(choices=[('vault', 'Qubix Vault'), ('shipped', 'Shipped to Address')], max_length=10)),
                ('payment_method', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT'), ('LTC', 'Litecoin')], max_length=20)),
                ('transaction_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Payment Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.physicalproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
