# Generated by Django 5.2.9 on 2026-04-01 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_physicalproduct_physicalholding_physicaltransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalproduct',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='physicaltransaction',
            name='service_type',
        ),
        migrations.AddField(
            model_name='physicalholding',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='core.physicaltransaction'),
        ),
        migrations.AddField(
            model_name='physicalproduct',
            name='three_d_model',
            field=models.URLField(blank=True, help_text='URL to 3D model file (gltf/glb)', null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='delivery_method',
            field=models.CharField(choices=[('vault', 'Qubix Vault Storage'), ('shipping', 'Ship to Address')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='documents_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='documents_sent_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='vault_location',
            field=models.CharField(blank=True, default='Zurich, Switzerland', max_length=100),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='vault_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='physicalproduct',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='physical_products/main/'),
        ),
        migrations.AlterField(
            model_name='physicalproduct',
            name='mint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='physicalproduct',
            name='purity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='physicalproduct',
            name='specification',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='physicalproduct',
            name='spot_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='physicalproduct',
            name='weight',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='physicaltransaction',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_confirmed', 'Payment Confirmed'), ('pending_approval', 'Pending Admin Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('vaulted', 'In Vault'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
        migrations.CreateModel(
            name='PhysicalCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.physicalcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.physicalproduct')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
