# Generated by Django 5.2.9 on 2026-04-01 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_physicalproduct_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('price_alert', 'Price Alert'), ('transaction', 'Transaction'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('dividend', 'Dividend'), ('system', 'System'), ('admin_alert', 'Admin Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
