# Generated by Django 5.2.9 on 2026-04-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicaltransaction',
            old_name='approved_at',
            new_name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='physicaltransaction',
            name='payment_proof',
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicaltransaction',
            name='status',
            field=models.CharField(choices=[('under_review', 'Payment Under Review'), ('confirmed_processing', 'Confirmed - Processing'), ('confirmed_vault', 'Confirmed - In Vault'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='under_review', max_length=20),
        ),
    ]
