# Generated by Django 5.2.9 on 2026-04-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_approved_at_physicaltransaction_confirmed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('processing', 'Processing'), ('packaged', 'Packaged'), ('transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='core.physicaltransaction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
