# Generated by Django 5.2.9 on 2026-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shippingtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaltransaction',
            name='crypto_currency_used',
            field=models.CharField(blank=True, help_text='Actual crypto currency used (BTC, ETH, USDT, LTC)', max_length=10, null=True),
        ),
    ]
