# Generated by Django 5.2.9 on 2026-04-05 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_physicaltransaction_crypto_currency_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('ceo', 'CEO / Director'), ('compliance', 'Compliance Officer'), ('custody', 'Chief Custody Officer'), ('underwriter', 'Underwriter')], max_length=50, unique=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('signer_name', models.CharField(max_length=200)),
                ('signer_title', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company Signatures',
            },
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_signature', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
