# Generated by Django 5.2.9 on 2026-04-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_companysignature_usersignature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySignature',
        ),
        migrations.AddField(
            model_name='physicalholding',
            name='verification_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='UserSignature',
        ),
    ]
