# Generated by Django 5.2.9 on 2026-04-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_companysignature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateproperty',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Example: 40.7128 for New York', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='realestateproperty',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Example: -74.0060 for New York', max_digits=10, null=True),
        ),
    ]
