# Generated by Django 5.2.9 on 2026-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_realestateproperty_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateinvestment',
            name='expected_annual_return',
            field=models.DecimalField(decimal_places=2, default=8.5, help_text='Expected annual return percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='realestateinvestment',
            name='expected_value_at_maturity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Projected value at the end of lock-in period', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='realestateinvestment',
            name='investment_period_months',
            field=models.IntegerField(default=12, help_text='Lock-in period in months'),
        ),
        migrations.AddField(
            model_name='realestateinvestment',
            name='maturity_date',
            field=models.DateTimeField(blank=True, help_text='Date when investment becomes withdrawable', null=True),
        ),
    ]
