# Generated by Django 5.2.9 on 2026-04-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_scheduledcall_supportticket_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcall',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number for the call", max_length=20, null=True),
        ),
    ]
