# Generated by Django 5.2.9 on 2026-04-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_scheduledcall_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override account creation date', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='override_updated_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override last update date', null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='override_average_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Admin can override average price', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='override_purchase_date',
            field=models.DateTimeField(blank=True, help_text='Admin can override purchase date', null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='override_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Admin can override quantity', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='physicalholding',
            name='override_current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin can override current value', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='physicalholding',
            name='override_purchase_date',
            field=models.DateTimeField(blank=True, help_text='Admin can override purchase date', null=True),
        ),
        migrations.AddField(
            model_name='physicalholding',
            name='override_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Admin can override quantity', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override transaction date', null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='override_total_amount',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Admin can override total amount', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='realestateinvestment',
            name='override_amount_invested',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin can override amount', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='realestateinvestment',
            name='override_invested_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override investment date', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override transaction date', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='override_total_amount',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Admin can override transaction amount', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='physicaltransaction',
            name='crypto_currency_used',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='physicaltransaction',
            name='delivery_method',
            field=models.CharField(choices=[('vault', 'Qubix Vault Storage'), ('shipping', 'Ship to Address'), ('sell', 'Sell Order')], max_length=10),
        ),
        migrations.AlterField(
            model_name='physicaltransaction',
            name='payment_method',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'USDT'), ('LTC', 'Litecoin'), ('delivery_fee', 'Delivery Fee'), ('sell_fee', 'Sell Fee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='physicaltransaction',
            name='status',
            field=models.CharField(choices=[('under_review', 'Payment Under Review'), ('confirmed_processing', 'Confirmed - Processing'), ('confirmed_vault', 'Confirmed - In Vault'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='under_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='realestateinvestment',
            name='expected_annual_return',
            field=models.DecimalField(decimal_places=2, default=8.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='realestateinvestment',
            name='expected_value_at_maturity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='realestateinvestment',
            name='personal_funded_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='realestateinvestment',
            name='personal_investor_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='realestateinvestment',
            name='personal_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='funded_percent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='investor_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='total_available',
            field=models.DecimalField(decimal_places=2, help_text='Total amount available for investment', max_digits=12),
        ),
    ]
