# Generated by Django 5.2.9 on 2026-04-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customuser_override_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodeposit',
            name='override_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override confirmation date', null=True),
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override creation date', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override notification date', null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override creation date', null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='override_triggered_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override triggered date', null=True),
        ),
        migrations.AddField(
            model_name='scheduledcall',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override call request date', null=True),
        ),
        migrations.AddField(
            model_name='scheduledcall',
            name='override_scheduled_date',
            field=models.DateField(blank=True, help_text='Admin can override scheduled date', null=True),
        ),
        migrations.AddField(
            model_name='scheduledcall',
            name='override_scheduled_time',
            field=models.CharField(blank=True, help_text='Admin can override scheduled time', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override message timestamp', null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override ticket creation date', null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='override_updated_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override last update date', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='override_approved_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override approval date', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override request date', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price_update_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='volatility',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='icon',
            field=models.CharField(default='💰', max_length=10),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='network',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='rate_usd',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='wallet_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='physicalproduct',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='physicalproduct',
            name='three_d_model',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realestateinvestment',
            name='investment_period_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='realestateinvestment',
            name='maturity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='realestateproperty',
            name='total_available',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='scheduledcall',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='auto_approve_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_auto_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='fee_crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
