# Generated by Django 5.2.9 on 2026-04-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cryptodeposit_override_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaltransaction',
            name='override_delivered_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override delivered date', null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='override_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Admin can override quantity', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='override_shipped_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override shipped date', null=True),
        ),
        migrations.AddField(
            model_name='physicaltransaction',
            name='override_shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin can override shipping fee', max_digits=10, null=True),
        ),
    ]
