# Generated by Django 5.2.9 on 2026-04-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_physicaltransaction_override_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatedividend',
            name='override_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin can override dividend amount', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='realestatedividend',
            name='override_month',
            field=models.DateField(blank=True, help_text='Admin can override month', null=True),
        ),
        migrations.AddField(
            model_name='realestatedividend',
            name='override_paid_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override payment date', null=True),
        ),
        migrations.AddField(
            model_name='realestateinvestment',
            name='override_expected_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin can override expected value at maturity', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='realestateinvestment',
            name='override_maturity_date',
            field=models.DateTimeField(blank=True, help_text='Admin can override maturity date', null=True),
        ),
        migrations.AddField(
            model_name='realestateinvestment',
            name='override_shares',
            field=models.IntegerField(blank=True, help_text='Admin can override number of shares', null=True),
        ),
        migrations.AddField(
            model_name='realestateproperty',
            name='override_annual_cash_flow',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin can override annual cash flow', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='realestateproperty',
            name='override_created_at',
            field=models.DateTimeField(blank=True, help_text='Admin can override creation date', null=True),
        ),
        migrations.AddField(
            model_name='realestateproperty',
            name='override_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admin can override purchase price', max_digits=20, null=True),
        ),
    ]
