# Generated by Django 5.2.9 on 2026-04-22 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('beginner', 'Beginner Guides'), ('market', 'Market Analysis'), ('platform', 'Platform Updates'), ('comparison', 'Comparisons')], default='beginner', max_length=50)),
                ('author_name', models.CharField(default='Qubix Team', max_length=100)),
                ('read_time', models.IntegerField(default=5)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
